/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Testframe.java
 *
 * Created on 19.05.2009, 23:01:46
 */

package arbeitsrechnungen;

/**
 *
 * @author markus
 */
public class Testframe extends javax.swing.JFrame {

    /** Creates new form Testframe */
    public Testframe() {
        initComponents();
        arbeitsstundenTabelle1 = new arbeitsrechnungen.ArbeitsstundenTabelle(this);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        arbeitsstundenTabelle1 = new arbeitsrechnungen.ArbeitsstundenTabelle(this);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N

        arbeitsstundenTabelle1.setName("arbeitsstundenTabelle1"); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(arbeitsstundenTabelle1, javax.swing.GroupLayout.DEFAULT_SIZE, 597, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(arbeitsstundenTabelle1, javax.swing.GroupLayout.DEFAULT_SIZE, 359, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Testframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private arbeitsrechnungen.ArbeitsstundenTabelle arbeitsstundenTabelle1;
    // End of variables declaration//GEN-END:variables

}
