/*
 * ArbeitsrechnungenAboutBox.java
 */

package de.kreth.arbeitsrechnungen.gui.dialogs;

import java.awt.event.ActionEvent;
import java.util.ResourceBundle;

import javax.swing.AbstractAction;
import javax.swing.ImageIcon;
import javax.xml.ws.Action;

public class ArbeitsrechnungenAboutBox extends javax.swing.JDialog {

   private static final long serialVersionUID = -6832189607221118736L;

   public ArbeitsrechnungenAboutBox(java.awt.Frame parent) {
      super(parent);
      initComponents();
      getRootPane().setDefaultButton(closeButton);
   }

   @Action
   public void closeAboutBox() {
      dispose();
   }

   /**
    * This method is called from within the constructor to
    * initialize the form.
    * WARNING: Do NOT modify this code. The content of this method is
    * always regenerated by the Form Editor.
    */
   // <editor-fold defaultstate="collapsed"
   // desc="Generated Code">//GEN-BEGIN:initComponents
   private void initComponents() {

      closeButton = new javax.swing.JButton();
      javax.swing.JLabel appTitleLabel = new javax.swing.JLabel();
      javax.swing.JLabel versionLabel = new javax.swing.JLabel();
      javax.swing.JLabel appVersionLabel = new javax.swing.JLabel();
      javax.swing.JLabel vendorLabel = new javax.swing.JLabel();
      javax.swing.JLabel appVendorLabel = new javax.swing.JLabel();
      javax.swing.JLabel homepageLabel = new javax.swing.JLabel();
      javax.swing.JLabel appHomepageLabel = new javax.swing.JLabel();
      javax.swing.JLabel appDescLabel = new javax.swing.JLabel();
      javax.swing.JLabel imageLabel = new javax.swing.JLabel();

      setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

      ResourceBundle resourceMap = ResourceBundle.getBundle(getClass().getSimpleName());

      setTitle(resourceMap.getString("title")); // NOI18N
      setModal(true);
      setName("aboutBox"); // NOI18N
      setResizable(false);

      closeButton.setAction(new AbstractAction(resourceMap.getString("closeAboutBox.Action.text")) {

         /**
			 * 
			 */
         private static final long serialVersionUID = 5874386517653009935L;

         @Override
         public void actionPerformed(ActionEvent e) {
            ArbeitsrechnungenAboutBox.this.setVisible(false);
         }
      }); // NOI18N
      closeButton.setName("closeButton"); // NOI18N

      appTitleLabel.setFont(appTitleLabel.getFont().deriveFont(appTitleLabel.getFont().getStyle() | java.awt.Font.BOLD, appTitleLabel.getFont().getSize() + 4));
      appTitleLabel.setText(resourceMap.getString("Application.title")); // NOI18N
      appTitleLabel.setName("appTitleLabel"); // NOI18N

      versionLabel.setFont(versionLabel.getFont().deriveFont(versionLabel.getFont().getStyle() | java.awt.Font.BOLD));
      versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
      versionLabel.setName("versionLabel"); // NOI18N

      appVersionLabel.setText(resourceMap.getString("Application.version")); // NOI18N
      appVersionLabel.setName("appVersionLabel"); // NOI18N

      vendorLabel.setFont(vendorLabel.getFont().deriveFont(vendorLabel.getFont().getStyle() | java.awt.Font.BOLD));
      vendorLabel.setText(resourceMap.getString("vendorLabel.text")); // NOI18N
      vendorLabel.setName("vendorLabel"); // NOI18N

      appVendorLabel.setText(resourceMap.getString("Application.vendor")); // NOI18N
      appVendorLabel.setName("appVendorLabel"); // NOI18N

      homepageLabel.setFont(homepageLabel.getFont().deriveFont(homepageLabel.getFont().getStyle() | java.awt.Font.BOLD));
      homepageLabel.setText(resourceMap.getString("homepageLabel.text")); // NOI18N
      homepageLabel.setName("homepageLabel"); // NOI18N

      appHomepageLabel.setText(resourceMap.getString("Application.homepage")); // NOI18N
      appHomepageLabel.setName("appHomepageLabel"); // NOI18N

      appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
      appDescLabel.setName("appDescLabel"); // NOI18N

      imageLabel.setIcon(new ImageIcon(resourceMap.getString("imageLabel.icon"))); // NOI18N
      imageLabel.setName("imageLabel"); // NOI18N

      javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
      getContentPane().setLayout(layout);
      layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
            layout.createSequentialGroup()
                  .addComponent(imageLabel)
                  .addGap(18, 18, 18)
                  .addGroup(
                        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                              .addGroup(
                                    javax.swing.GroupLayout.Alignment.LEADING,
                                    layout.createSequentialGroup()
                                          .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(versionLabel).addComponent(vendorLabel)
                                                      .addComponent(homepageLabel))
                                          .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                          .addGroup(
                                                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(appVersionLabel).addComponent(appVendorLabel)
                                                      .addComponent(appHomepageLabel))).addComponent(appTitleLabel, javax.swing.GroupLayout.Alignment.LEADING)
                              .addComponent(appDescLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE)
                              .addComponent(closeButton)).addContainerGap()));
      layout.setVerticalGroup(layout
            .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(
                  layout.createSequentialGroup().addContainerGap().addComponent(appTitleLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(appDescLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(versionLabel).addComponent(appVersionLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(vendorLabel).addComponent(appVendorLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(homepageLabel).addComponent(appHomepageLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE).addComponent(closeButton).addContainerGap()));

      pack();
   }// </editor-fold>//GEN-END:initComponents

   // Variables declaration - do not modify//GEN-BEGIN:variables
   private javax.swing.JButton closeButton;
   // End of variables declaration//GEN-END:variables

}
